const createPerson = (name, age) => ({name, age});
const createBook = ( title, pages) => ({title, pages, isLong: pages > 300});
const wrap = (value) => ({value});
const person = createPerson('gigi', 25);
console.log(person);
console.log(person.name);
console.log(createPerson('nino', 30).age);
console.log(createBook('the hobbit', 310));
console.log(createBook('the little prince', 96));
console.log(wrap(5));